apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: miniware-celery-worker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CELERY_BROKER_URL
          value: "amqp://miniware:miniware_password@rabbitmq:5672//"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"
        - name: API_BASE_URL
          value: "http://api-service:8000"
        - name: PYTHONPATH
          value: "/app"
        volumeMounts:
        - name: shared-data
          mountPath: /app/shared
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
