apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
      - name: django-migrations
        image: miniware-api:latest
        command: ["python", "manage.py", "migrate"]
        env:
        - name: CELERY_BROKER_URL
          value: "amqp://miniware:miniware_password@rabbitmq:5672//"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"
      restartPolicy: Never
  backoffLimit: 4
